### ISSUE TITLE
Make an GUI to add custom themes

### ISSUE THREAD

**Issue by codic12** [themix-project/themix-gui#279] opened 2019-12-07 00:38 UTC
It's not hard to make a GUI to do this, if we can with plugins. Not sure why https://github.com/themix-project/oomox/issues/146 was closed...
For example, I'd like to see Qogir, but I don't know how to make a plugin. The same goes with the OSX Gtk themes.
Finally, can we add an option to change the titlebar buttons in the headerbar? The close, minimize, and maximize buttons, at least in Materia, get the buttons from the icon theme... a feature to add custom SVGs would be greatly appreciated, by me at the least...

**Comment by gsbhasin123** [comment] 2019-12-07 16:05
What's good first issue @actionless ?

**Comment by actionless** [comment] 2019-12-07 16:35
as i'm not using any of the things you listed i don't have any interest to work on them, so it could be a `good first issue` for a new contributor

see also: https://help.github.com/en/github/building-a-strong-community/helping-new-contributors-find-your-project-with-labels

**Comment by actionless** [comment] 2019-12-07 16:36
also i recommend to change the issue headline to be more descriptive

**Comment by actionless** [comment] 2023-01-05 00:49
duplicate of https://github.com/themix-project/themix-gui/issues/33

**Closed by actionless** 2023-01-05 00:49 UTC
Labels: good first issue, plugins
