### ISSUE TITLE
Suru++ themes not being created

### ISSUE THREAD

**Issue by ghost** [themix-project/themix-gui#353] opened 2021-01-16 15:42 UTC
Hi,
My system is a Ryzen 7 2700, MSI RX-580 running ArcoLinux i3 on the latest kernel, up to date, Nemo as go-to file manager, Thunar used occasionally. Regardless the theme I create or file manager, Suru++ icon themes only show as a template style, white on blue as shown in this [screenie](https://thenextpoetician.blogspot.com/2021/01/suru-icon-theme-created-in-oomox.html). Sorry for not providing more initial info, but I'm not so good at poking under the hood about something like this, so please let me know what you need to know to figure this out. Thanks.

**Comment by poetician** [comment] 2021-04-09 03:39
This is the output from a recent attempt:

> Traceback (most recent call last):
  File "/opt/oomox/oomox_gui/colors_list.py", line 563, in _callback
    each(key, value)
  File "/opt/oomox/oomox_gui/colors_list.py", line 530, in color_edited
    self.color_edited_callback(self.theme)
  File "/opt/oomox/oomox_gui/main.py", line 405, in on_color_edited
    self.load_colorscheme(colorscheme)
  File "/opt/oomox/oomox_gui/main.py", line 342, in load_colorscheme
    self.generate_terminal_colors(callback=self._load_colorscheme_callback)
  File "/opt/oomox/oomox_gui/main.py", line 399, in generate_terminal_colors
    generate_terminal_colors_for_oomox(
  File "/opt/oomox/oomox_gui/terminal.py", line 507, in generate_terminal_colors_for_oomox
    _generate_themes_from_oomox(
  File "/opt/oomox/oomox_gui/terminal.py", line 458, in _generate_themes_from_oomox
    term_colorscheme = generate_theme_from_hint(
  File "/opt/oomox/oomox_gui/terminal.py", line 90, in generate_theme_from_hint
    _closest_key, diff = find_closest_color_key(
  File "/opt/oomox/oomox_gui/terminal.py", line 41, in find_closest_color_key
    diff = ColorDiff(preset_color, color_hex)
  File "/opt/oomox/oomox_gui/color.py", line 73, in __init__
    color_list_2 = color_list_from_hex(theme_color_2)
  File "/opt/oomox/oomox_gui/color.py", line 13, in color_list_from_hex
    return [color_text[:2], color_text[2:4], color_text[4:]]
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/opt/oomox/oomox_gui/colors_list.py", line 563, in _callback
    each(key, value)
  File "/opt/oomox/oomox_gui/colors_list.py", line 530, in color_edited
    self.color_edited_callback(self.theme)
  File "/opt/oomox/oomox_gui/main.py", line 405, in on_color_edited
    self.load_colorscheme(colorscheme)
  File "/opt/oomox/oomox_gui/main.py", line 342, in load_colorscheme
    self.generate_terminal_colors(callback=self._load_colorscheme_callback)
  File "/opt/oomox/oomox_gui/main.py", line 399, in generate_terminal_colors
    generate_terminal_colors_for_oomox(
  File "/opt/oomox/oomox_gui/terminal.py", line 507, in generate_terminal_colors_for_oomox
    _generate_themes_from_oomox(
  File "/opt/oomox/oomox_gui/terminal.py", line 458, in _generate_themes_from_oomox
    term_colorscheme = generate_theme_from_hint(
  File "/opt/oomox/oomox_gui/terminal.py", line 90, in generate_theme_from_hint
    _closest_key, diff = find_closest_color_key(
  File "/opt/oomox/oomox_gui/terminal.py", line 41, in find_closest_color_key
    diff = ColorDiff(preset_color, color_hex)
  File "/opt/oomox/oomox_gui/color.py", line 76, in __init__
    channel_2 = hex_to_int(color_list_2[channel_index])
  File "/opt/oomox/oomox_gui/color.py", line 5, in hex_to_int
    return int("0x{}".format(text), 0)
ValueError: invalid literal for int() with base 0: '0x'
Traceback (most recent call last):
  File "/opt/oomox/oomox_gui/colors_list.py", line 563, in _callback
    each(key, value)
  File "/opt/oomox/oomox_gui/colors_list.py", line 530, in color_edited
    self.color_edited_callback(self.theme)
  File "/opt/oomox/oomox_gui/main.py", line 405, in on_color_edited
    self.load_colorscheme(colorscheme)
  File "/opt/oomox/oomox_gui/main.py", line 342, in load_colorscheme
    self.generate_terminal_colors(callback=self._load_colorscheme_callback)
  File "/opt/oomox/oomox_gui/main.py", line 399, in generate_terminal_colors
    generate_terminal_colors_for_oomox(
  File "/opt/oomox/oomox_gui/terminal.py", line 507, in generate_terminal_colors_for_oomox
    _generate_themes_from_oomox(
  File "/opt/oomox/oomox_gui/terminal.py", line 458, in _generate_themes_from_oomox
    term_colorscheme = generate_theme_from_hint(
  File "/opt/oomox/oomox_gui/terminal.py", line 90, in generate_theme_from_hint
    _closest_key, diff = find_closest_color_key(
  File "/opt/oomox/oomox_gui/terminal.py", line 41, in find_closest_color_key
    diff = ColorDiff(preset_color, color_hex)
  File "/opt/oomox/oomox_gui/color.py", line 76, in __init__
    channel_2 = hex_to_int(color_list_2[channel_index])
  File "/opt/oomox/oomox_gui/color.py", line 5, in hex_to_int
    return int("0x{}".format(text), 0)
ValueError: invalid literal for int() with base 0: '0x'
Traceback (most recent call last):
  File "/opt/oomox/oomox_gui/colors_list.py", line 563, in _callback
    each(key, value)
  File "/opt/oomox/oomox_gui/colors_list.py", line 530, in color_edited
    self.color_edited_callback(self.theme)
  File "/opt/oomox/oomox_gui/main.py", line 405, in on_color_edited
    self.load_colorscheme(colorscheme)
  File "/opt/oomox/oomox_gui/main.py", line 342, in load_colorscheme
    self.generate_terminal_colors(callback=self._load_colorscheme_callback)
  File "/opt/oomox/oomox_gui/main.py", line 399, in generate_terminal_colors
    generate_terminal_colors_for_oomox(
  File "/opt/oomox/oomox_gui/terminal.py", line 507, in generate_terminal_colors_for_oomox
    _generate_themes_from_oomox(
  File "/opt/oomox/oomox_gui/terminal.py", line 458, in _generate_themes_from_oomox
    term_colorscheme = generate_theme_from_hint(
  File "/opt/oomox/oomox_gui/terminal.py", line 90, in generate_theme_from_hint
    _closest_key, diff = find_closest_color_key(
  File "/opt/oomox/oomox_gui/terminal.py", line 41, in find_closest_color_key
    diff = ColorDiff(preset_color, color_hex)
  File "/opt/oomox/oomox_gui/color.py", line 76, in __init__
    channel_2 = hex_to_int(color_list_2[channel_index])
  File "/opt/oomox/oomox_gui/color.py", line 5, in hex_to_int
    return int("0x{}".format(text), 0)
ValueError: invalid literal for int() with base 0: '0x'
Traceback (most recent call last):
  File "/opt/oomox/oomox_gui/colors_list.py", line 563, in _callback
    each(key, value)
  File "/opt/oomox/oomox_gui/colors_list.py", line 530, in color_edited
    self.color_edited_callback(self.theme)
  File "/opt/oomox/oomox_gui/main.py", line 405, in on_color_edited
    self.load_colorscheme(colorscheme)
  File "/opt/oomox/oomox_gui/main.py", line 342, in load_colorscheme
    self.generate_terminal_colors(callback=self._load_colorscheme_callback)
  File "/opt/oomox/oomox_gui/main.py", line 399, in generate_terminal_colors
    generate_terminal_colors_for_oomox(
  File "/opt/oomox/oomox_gui/terminal.py", line 507, in generate_terminal_colors_for_oomox
    _generate_themes_from_oomox(
  File "/opt/oomox/oomox_gui/terminal.py", line 458, in _generate_themes_from_oomox
    term_colorscheme = generate_theme_from_hint(
  File "/opt/oomox/oomox_gui/terminal.py", line 90, in generate_theme_from_hint
    _closest_key, diff = find_closest_color_key(
  File "/opt/oomox/oomox_gui/terminal.py", line 41, in find_closest_color_key
    diff = ColorDiff(preset_color, color_hex)
  File "/opt/oomox/oomox_gui/color.py", line 76, in __init__
    channel_2 = hex_to_int(color_list_2[channel_index])
  File "/opt/oomox/oomox_gui/color.py", line 5, in hex_to_int
    return int("0x{}".format(text), 0)
ValueError: invalid literal for int() with base 0: '0x'

**Comment by gusbemacbe** [comment] 2021-04-09 03:51
I am creator of Suru++. I didn't update Suru++ for a year because I'm focusing more on Adwaita++ and Yaru++. 

I don't know when I can update Suru++.

**Comment by poetician** [comment] 2021-04-09 13:04
Fair enough. Thanks for responding.

**Comment by actionless** [comment] 2021-04-26 11:42
your latest error log doesnt seems to be related to icon theme

make sure you're using latest themix gui from git

if its still reproducing, please upload the themix palette which causing that issue

**Comment by gusbemacbe** [comment] 2022-03-01 05:16
@actionless 

You can close this issue as my Suru++ icons are discontinued.

**Closed** 2023-01-05 00:46 UTC
Labels: need info, submitter gone
